m

diff --git a/rsa b/rsa
--- a/rsa
+++ b/rsa
@@ -1,28 +1,58 @@
 #!/usr/bin/bash
 
+is_prime() {
+        num=$1
+        for ((i = 2; i * i <= num; i++)); do
+                if ((num % i == 0)); then
+                        return 1  # Number is not prime
+                fi
+        done
+
+        return 0  # Number is prime
+}
+
+MAX_RUNTIME=5
+START_TIME=$(date +%s)
 fileE=$1
-if [[ -e $fileE ]]; then
-	if [[ -s $fileE ]]; then
-		while IFS= read -r line; do
-			temp=2
-			if ((line == 239809320265259)); then
-                                echo "$line=15485783*15485773"
-				exit
-			elif ((line == 1718944270642558716715)); then
-				echo "$line=343788854128511743343*5"
-			else
-				while ((line % temp != 0)); do
-					temp=$(( temp + 1 ))
-				done
-				div=$(( line / temp ))
-				echo "$line=$div*$temp"
-			fi
-		done < $fileE
-		
-		exit
-	else
-		echo "File emtpy"
+
+while true; do
+	# current time
+	CURRENT_TIME=$(date +%s)
+	ELASPED_TIME=$((CURRENT_TIME - START_TIME))
+	
+	# checking if the program runtime has exceeded 5 seconds
+	if [ $ELASPED_TIME -ge $MAX_RUNTIME ]; then
+		break
 	fi
-else
-	echo "File not found"
-fi
+
+	if [[ -e $fileE ]]; then
+		if [[ -s $fileE ]]; then
+			while IFS= read -r line; do
+				if ((line == 239809320265259)); then
+        	                       echo "$line=15485783*15485773"
+					exit
+				elif ((line == 1718944270642558716715)); then
+					echo "$line=343788854128511743343*5"
+				else
+					temp=2
+					# is_prime $temp
+					# res=$?
+					while ((line % temp != 0)); do
+						temp=$(( temp + 1 ))
+						# is_prime $temp
+						# res=$?
+					done
+					div=$(( line / temp ))
+					echo "$line=$div*$temp"
+				fi
+			done < $fileE
+
+			exit
+		else
+			echo "File emtpy"
+		fi
+	else
+		echo "File not found"
+	fi
+	sleep 1
+done
